"""empty message

Revision ID: 798645c92166
Revises: 212a734951d8
Create Date: 2022-04-08 14:30:30.887591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798645c92166'
down_revision = '212a734951d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_night',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('game', sa.String(length=140), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_night')
    # ### end Alembic commands ###
